services:
  product-command-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=product'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  user-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
  stock-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=stock'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'
  order-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=order'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5435:5432'