spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5435/stock
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  kafka:
    consumer:
      order-created:
        created:
          topic: ac_order_service.order-created.create
      order-cancelled:
        created:
          topic: ac_order_service.order-cancelled.create
      order-updated:
        created:
          topic: ac_order_service.order-updated.create
    producer:
      stock-update-failed:
        created:
          topic: ac_stock-service.stock-update-failed.created
    config:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: stock-service
        auto-offset-reset: earliest
        enable-auto-commit: false
        trusted-packages: '*'
      producer:
        acks: "1"
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  servlet:
    context-path: /stock-service
  port: 8083
