apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/awesome-commerce-keycloak: "true"
        io.kompose.network/awesome-commerce-service-network: "true"
        io.kompose.service: keycloak
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              value: secret
            - name: DB_USER
              value: user
          image: jboss/keycloak
          name: keycloak
          ports:
            - containerPort: 8443
              hostPort: 18443
              protocol: TCP
            - containerPort: 8080
              hostPort: 28080
              protocol: TCP
            - containerPort: 9990
              hostPort: 19990
              protocol: TCP
      restartPolicy: Always
