apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: redpanda
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redpanda
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/awesome-commerce-default: "true"
        io.kompose.service: redpanda
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERS
              value: kafka:29092
          image: docker.redpanda.com/redpandadata/console:latest
          name: redpanda-console
          ports:
            - containerPort: 8080
              hostPort: 8090
              protocol: TCP
      restartPolicy: Always
