scrape_configs:
  - job_name: 'AwesomeCommerceMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['gateway:8080']
        labels:
          application: 'Awesome Commerce Gateway Application'