spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://user-db:5435/user
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

server:
  port: 8083