spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://order-db/order
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  kafka:
    consumer:
      order-status-update:
        created:
          topic: ac_shipment-service.order-status-update.created
      stock-update-failed:
        created:
          topic: ac_stock-service.stock-update-failed.created
    producer:
      order-created:
        created:
          topic: ac_order_service.order-created.create
      order-cancelled:
        created:
          topic: ac_order_service.order-cancelled.create
      order-updated:
        created:
          topic: ac_order_service.order-updated.create
    config:
      bootstrap-servers: kafka:9092
      consumer:
        group-id: order-service
        auto-offset-reset: earliest
        enable-auto-commit: false
        trusted-packages: '*'
      producer:
        acks: "1"
  data:
    redis:
      host: redis
      port: 6379


feign:
  client:
    config:
      stock-service:
        url: http://stock-service/stock-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server/eureka/

server:
  servlet:
    context-path: /order-service
  port: 8081