spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://product-db/product
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server/eureka/
server:
  servlet:
    context-path: /product-service
  port: 8082
